import java.time.Instant

plugins {
    id("net.minecraftforge.gradle") version "[6.0,6.2)"
    id("org.parchmentmc.librarian.forgegradle") version "1.+"
}

version = "0.1.1-SNAPSHOT+1.20.1" // https://semver.org/
group = "com.lightning.northstar" // http://maven.apache.org/guides/mini/guide-naming-conventions.html
//archivesBaseName = "northstar"

// Include resources generated by data generators.
sourceSets.main {
    resources.srcDir("src/generated/resources")
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
    maven("https://modmaven.dev/")
    maven("https://maven.tterrag.com/")
    maven("https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/") // GeckoLib
    maven("https://maven.blamejared.com/") // JEI
}

dependencies {
    minecraft("net.minecraftforge:forge:1.20.1-47.4.0")

    // TODO: regroup versions in a separate place
    compileOnly(fg.deobf("com.simibubi.create:create-1.20.1:6.0.6-205:slim"))
    compileOnly(fg.deobf("com.tterrag.registrate:Registrate:MC1.20-1.3.3"))
    compileOnly(fg.deobf("com.jozufozu.flywheel:flywheel-forge-1.20.1:1.0.0-beta-88"))
    compileOnly(fg.deobf("software.bernie.geckolib:geckolib-forge-1.20.1:4.7.2"))
    compileOnly(fg.deobf("mezz.jei:jei-1.20.1-forge-api:15.20.0.112"))
}

minecraft {
    //mappings("official", "1.20.1")
    mappings("parchment", "2023.09.03-1.20.1")

    // accessTransformer = file("src/main/resources/META-INF/accesstransformer.cfg") // Currently, this location cannot be changed from the default.

    runs {
        create("client") {
            workingDirectory(project.file("run"))

            properties(mapOf(
                "forge.logging.workers" to "REGISTRIES",

                "forge.logging.console.level" to "debug",
                "mixin.env.remapRefMap" to "true",
                "mixin.env.refMapRemappingFile" to "${projectDir}/build/createSrgToMcp/output.srg",

                "forge.enabledGameTestNamespaces" to "northstar",
            ))

            /*mods {
                "northstar" {
                    source(sourceSets.main.get())
                }
            }*/
        }
        create("server") {
            workingDirectory(project.file("run"))

            properties(mapOf(
                "forge.logging.markers" to "REGISTRIES",

                "forge.logging.console.level" to "debug",
                "mixin.env.remapRefMap" to "true",
                "mixin.env.refMapRemappingFile" to "${projectDir}/build/createSrgToMcp/output.srg",

                "forge.enabledGameTestNamespaces" to "northstar",
            ))

            /*mods {
                "northstar" {
                    source(sourceSets.main.get())
                }
            }*/
        }
    }

    /*runs {
        data {
            workingDirectory project . file ("run")

            property "forge.logging.markers", "REGISTRIES"
            property "forge.logging.console.level", "debug"

            // Specify the modid for data generation, where to output the resulting resource, and where to look for existing resources.
            args "--mod", "northstar", "--all", "--output", file("src/generated/resources/"), "--existing", file("src/main/resources/")

            mods {
                northstar {
                    source sourceSets . main
                }
            }
        }
    }*/
}

tasks.jar {
    finalizedBy("reobfJar")

    manifest {
        attributes(mapOf(
            "Specification-Title" to "northstar",
            "Specification-Vendor" to "lightning",
            "Specification-Version" to version,
            "Implementation-Title" to project.name,
            "Implementation-Version" to version,
            "Implementation-Vendor" to "lightning",
            "Implementation-Timestamp" to Instant.now().toString()
        ))
    }
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}
