modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT"
issueTrackerURL = "https://github.com/Redstonneur1256/Northstar-Redux/issues"


[[mods]]
modId = "northstar"
displayTest = "MATCH_VERSION"
version = "${file.jarVersion}"

displayName = "Northstar Redux"
displayURL = "https://modrinth.com/project/northstar-redux"
logoFile = "logo.png"
credits = "Original mod by lightning2401."
authors = "Redstonneur1256"
description = '''
Inspired by Micdoodle's Galacticraft, Northstar seeks to return players to the stars with the power of the Create mod. 
'''

[[dependencies.northstar]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.northstar]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.northstar]]
modId = "create"
mandatory = true
versionRange = "[6.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.northstar]]
modId = "geckolib"
mandatory = true
versionRange = "[4.7,5.0)"
ordering = "NONE"
side = "BOTH"
